### ISSUE TITLE
ask for lib and include files

### ISSUE THREAD

**Issue by ddxu** [laMia482/tensorflow_cc-API#1]
@laMia482  Thank your for your project~
I've been trying to compile tensorflow C++ dynamic library in linux too , but occur some problems. Could you share your lib and include files for this repo？ They are just links here. Thank you~ Hope for your reply~

**Comment by lamia482** [comment]
Yep, I just uploaded at https://drive.google.com/open?id=0B9BHx-TgQtxjcXhEQU5YazVnbWM
Try to down it, if failed, uhm.. 
Thanks for your attention.

-laMia

发件人: ddxu
发送时间: 2017年8月15日 10:26
收件人: laMia482/tensorflow_cc-API
抄送: Subscribed
主题: [laMia482/tensorflow_cc-API] ask for lib and include files (#1)

I've been trying to compile tensorflow C++ dynamic library in linux too , but occur some problems. Could you share your lib and include files for this repo？ They are just links here. Thank you~ Hope for your reply~
